platform :osx, '10.9'

xcodeproj "NewtonCommanderQuark"

target "Demo" do
  pod "newton-commander-quark", :path => "../newton-commander-quark.podspec"
end

target "Tests" do
  pod "newton-commander-quark", :path => "../newton-commander-quark.podspec"
end
